# ██████╗ ███╗   ███╗██████╗ ██╗     ██╗   ██╗ ██████╗
# ██╔══██╗████╗ ████║██╔══██╗██║     ██║   ██║██╔════╝
# ██████╔╝██╔████╔██║██████╔╝██║     ██║   ██║╚█████╗
# ██╔═══╝ ██║╚██╔╝██║██╔═══╝ ██║     ██║   ██║ ╚═══██╗
# ██║     ██║ ╚═╝ ██║██║     ███████╗╚██████╔╝██████╔╝
# ╚═╝     ╚═╝     ╚═╝╚═╝     ╚══════╝ ╚═════╝ ╚═════╝
# Plugin by Kyoku


Options:
  AllowSelfMessage: false
  # more options will come in future updates

Messages:
  MessageToSender: "&e(To &6%vault_prefix%%recipient%&e) &f%message%"
  MessageToRecipient: "&e(From &6%vault_prefix%%sender%&e) &f%message%"
  NoReplyTarget: "&cNo one has messaged you."
  RecipientMessagesOff: "&c%vault_prefix%%recipient% currently has their messages off."
  MessagesToggledOn: "&aYou will now receive messages."
  MessagesToggledOff: "&cYou will no longer receive messages."
  SocialSpyEnabled: "&aYou have enabled social spy."
  SocialSpyDisabled: "&cYou have disabled social spy."
  SocialSpyFormat: "&e[SPY] (&6%vault_prefix%%sender% &eto &6%vault_prefix%%recipient%&e) &f%message%"
  MessageCommandUsage: "&cInvalid arguments: &7/msg <player> <message>"
  ReplyCommandUsage: "&cInvalid arguments: &7/r <message>"
  NoPermission: "&cYou do not have permission to use that command."
  PlayerNotFound: "&cThe player %recipient% could not be found."
  CannotMessageSelf: "&cYou cannot message yourself!"