name: PMPlus
version: 1.1.0
main: dev.prinke.pmplus.PMPlus
api-version: 1.18
authors: [ Prinke ]
description: A super customizable messaging plugin
website: prinke.dev
softdepend:
  - PlaceholderAPI
  - SuperVanish
  - PremiumVanish
commands:
  message:
    description: Privately message a player
    permission: pmplus.msg
    aliases:
      - pm
      - msg
      - whisper
      - tell
      - w
  togglepms:
    description: Toggle whether you can receive messages
    permission: pmplus.toggle
    aliases:
      - togglemsgs
      - togglepm
  socialspy:
    description: Spy on other players' conversations.
    permission: pmplus.socialspy
    aliases:
      - spy
  reply:
    description: Reply to a previous message.
    permission: pmplus.reply
    aliases:
      - r
  pmmute:
    description: Prevent players from sending messages
    permission: pmplus.mute
    aliases:
      - msgmute
      - mmute
      - pmute

permissions:
  pmplus.msg:
    description: Allows a player to message another player.
    default: true
  pmplus.toggle:
    description: Allows a player to toggle whether they can receive private messages.
    default: true
  pmplus.bypass:
    description: Allows a player to still message players who have their messages off.
    default: op
  pmplus.socialspy:
    description: Allows players to spy on other players' conversations.
    default: op
  pmplus.reply:
    description: Allows players to reply to a previous message
    default: true
  pmplus.mute:
    description: Allows staff to mute players from sending messages
    default: op